"""Subclass of MainDialog, which is generated by wxFormBuilder."""

import wx
import os
import MainDialog
import FileDropTarget
import ImageTools
import ImageViewAndGrid
import ImageClipInfoJsonReader
from PIL import Image, ImageDraw, ImageFont

# Implementing MainDialog
def GetColorTupleFromPicker(color_picker):
    c = color_picker.GetColour()
    return c.GetRed(), c.GetGreen(), c.GetBlue()


class ImageWizardMainDialog(MainDialog.MainDialog):
    def __init__(self, parent):
        MainDialog.MainDialog.__init__(self, parent)
        drop_target = FileDropTarget.FileDropTarget(self.m_listBoxSrcImage, self.m_dirPickerOutputDir)
        self.m_listBoxSrcImage.SetDropTarget(drop_target)
        self.m_comboBoxSuffix.Append(".png")
        self.m_comboBoxSuffix.Append(".tga")
        self.m_comboBoxSuffix.Append(".jpg")
        self.m_comboBoxSuffix.Append(".bmp")
        self.m_comboBoxSuffix.SetValue(".png")
        self.m_ImageViewAndGrid = ImageViewAndGrid.ImageViewAndGrid(self.m_scrolledWindowImageViewAndGrid)
        self._InitClipInfoListControl()
        self.m_clipInfoData = {}
        self.m_comboBoxClipInfo.Bind(wx.EVT_COMBOBOX, self.OnComboBoxClipInfoSelected)
        self.m_colourPickerTransparent.SetColour(wx.Colour(247, 0, 255))

    def _InitClipInfoListControl(self):
        # 获取HeaderCtrl并设置属性
        self.m_listCtrlClipInfo.InsertColumn(0, u"图块文件名", width=100)  # 最简单的列头
        self.m_listCtrlClipInfo.InsertColumn(1, u"图块左上X", width=70)
        self.m_listCtrlClipInfo.InsertColumn(2, u"图块左上Y", width=70)
        self.m_listCtrlClipInfo.InsertColumn(3, u"图块宽度", width=60)
        self.m_listCtrlClipInfo.InsertColumn(4, u"图块高度", width=60)

    # 点击【<-添加已处理图片】按钮
    def OnButtonAddProcessFilesClicked(self, event):
        # 弹出文件选择对话框
        with wx.FileDialog(self, "选择图片文件", wildcard="图片文件 (*.png)|*.png",
                           style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST | wx.FD_MULTIPLE) as file_dialog:
            if file_dialog.ShowModal() == wx.ID_CANCEL:
                return

            output_file_paths = file_dialog.GetPaths()  # 获取选择的文件路径
            for path in output_file_paths:
                self.m_listBoxOutputFiles.Append(path)

    # 点击【打开图片裁切信息文件->】按钮
    def OnButtonLoadClipInfoFileClicked(self, event):
        with wx.FileDialog(self, "选择JSON文件", wildcard="JSON文件 (*.json)|*.json",
                           style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST) as file_dialog:
            if file_dialog.ShowModal() == wx.ID_CANCEL:
                return

            file_path = file_dialog.GetPath()
            self.m_clipInfoData = ImageClipInfoJsonReader.ReadClipInfoJsonFile(file_path)

            if self.m_clipInfoData:
                self.m_comboBoxClipInfo.Clear()
                for clip_type in self.m_clipInfoData.keys():
                    self.m_comboBoxClipInfo.Append(clip_type)

                if self.m_comboBoxClipInfo.GetCount() > 0:
                    self.m_comboBoxClipInfo.SetSelection(0)
                    self._LoadClipInfoToGrid(self.m_clipInfoData[self.m_comboBoxClipInfo.GetValue()])

    # 组合框选择切片类型事件
    def OnComboBoxClipInfoSelected(self, event):
        selected_type = self.m_comboBoxClipInfo.GetValue()
        if selected_type and selected_type in self.m_clipInfoData:
            self._LoadClipInfoToGrid(self.m_clipInfoData[selected_type])

    def _LoadClipInfoToGrid(self, clip_info_list):
        self.m_listCtrlClipInfo.DeleteAllItems()
        for idx, item in enumerate(clip_info_list):
            row = self.m_listCtrlClipInfo.InsertItem(idx, item['name'])
            self.m_listCtrlClipInfo.SetItem(row, 0, item['name'])
            self.m_listCtrlClipInfo.SetItem(row, 1, str(item['left_top_x']))
            self.m_listCtrlClipInfo.SetItem(row, 2, str(item['left_top_y']))
            self.m_listCtrlClipInfo.SetItem(row, 3, str(item['width']))
            self.m_listCtrlClipInfo.SetItem(row, 4, str(item['height']))

    # 【点击执行切片】
    def OnButtonDoClipClicked(self, event):
        entire_img_path = self.m_listBoxOutputFiles.GetStringSelection()  # 获取第一个选中行的索引

        if not entire_img_path:
            return

        entire_img_dir = os.path.dirname(entire_img_path)  # 原图片的所在目录
        row_count = self.m_listCtrlClipInfo.GetItemCount()
        col_count = self.m_listCtrlClipInfo.GetColumnCount()
        entire_img = ImageTools.get_rgba_img(entire_img_path)

        if entire_img is None:
            return

        for row in range(row_count):
            row_data = []
            for col in range(col_count):
                item_text = self.m_listCtrlClipInfo.GetItemText(row, col)
                row_data.append(item_text)

            # 读取到参数，准备切片并保存图片
            tile_file_path = os.path.normpath(os.path.join(entire_img_dir, row_data[0] + ".png"))
            left_top_x = int(row_data[1])
            left_top_y = int(row_data[2])
            width = int(row_data[3])
            height = int(row_data[4])
            ImageTools.crop_one_tile_from_entire_image(entire_img, left_top_x, left_top_y, width, height,
                                                       tile_file_path)

        wx.MessageBox("对图片切片执行完毕！", "OK", wx.OK)

    def OnButtonGenerateClicked(self, event):
        print("click=========")
        self.GenerateNewImage()

    def OnButtonClearSrcImageListBoxClicked(self, event):
        self.m_listBoxSrcImage.Clear()

    def OnButtonClearOutputFileListBoxClicked(self, event):
        self.m_listBoxOutputFiles.Clear()

    def OnButtonClearSrcOutputMessageClicked(self, event):
        self.m_textCtrlOutputMessage.Clear()

    def OnImageViewAndGridFileChanged(self, event):
        print("OnImageViewAndGridFileChanged")
        self.m_ImageViewAndGrid.load_image(self.GetViewAndGridImageFilePath())

    def OnTextCtrlViewGridWidthTextEnter(self, event):
        v = int(self.m_textCtrlViewGridWidth.GetValue())
        self.m_ImageViewAndGrid.set_w_interval(v)
        self.m_ImageViewAndGrid.RefreshWindow()

    def OnTextCtrlViewGridHeightTextEnter(self, event):
        v = int(self.m_textCtrlViewGridHeight.GetValue())
        self.m_ImageViewAndGrid.set_h_interval(v)
        self.m_ImageViewAndGrid.RefreshWindow()

    # 是否绘制网格线
    def OnCheckBoxViewAndGrid(self, event):
        self.m_ImageViewAndGrid.SetIsDrawViewGrid(not self.m_ImageViewAndGrid.GetIsDrawViewGrid())
        self.m_ImageViewAndGrid.RefreshWindow()

    def OnImageViewGridLineColorChanged(self, event):
        self.m_ImageViewAndGrid.SetGridLineColor(
            self.m_colourPickerGridLine.GetColour())  # self.m_colourPickerGridLine.GetValue())
        self.m_ImageViewAndGrid.RefreshWindow()

    # 点击裁剪按钮
    def OnButtonSplitImageClicked(self, event):
        # 拿到输出路径，如果没有，就以当前工作目录作为路径
        split_cell_output = self.GetSplitCellImageOutputPath()
        split_cell_name = self.GetSplitCellName()
        tile_width = self.GetSplitCellWidth()
        tile_height = self.GetSplitCellHeight()
        output_dir = self.GetSplitCellImageOutputPath()
        # output_dir = "D:/MyProjects/SaveYueFei/Arts/battle_scene/battle_scene_100"
        img = ImageTools.get_rgba_img(self.GetViewAndGridImageFilePath())
        # img = ImageTools.get_rgba_img("E:/download/Tile-AA.png")
        ImageTools.split_image_into_tiles(img, tile_width, tile_height, split_cell_name, output_dir)
        wx.MessageBox("完成分割图片！", "OK", wx.OK)

    # 生成文字图片
    def OnButtonClickGenerateSingleTextImage(self, event):
        self.generate_text_image()
        self.on_save_text_image()

    def wrap_text(self, text, font, max_width):
        """将文本换行以适应最大宽度"""
        words = text.split()
        lines = []
        current_line = []

        # 创建一个临时ImageDraw对象来测量文本
        temp_image = Image.new('RGB', (1, 1))
        temp_draw = ImageDraw.Draw(temp_image)

        for word in words:
            test_line = ' '.join(current_line + [word])
            bbox = temp_draw.textbbox((0, 0), test_line, font=font)
            line_width = bbox[2] - bbox[0]

            if line_width <= max_width:
                current_line.append(word)
            else:
                if current_line:
                    lines.append(' '.join(current_line))
                current_line = [word]

        if current_line:
            lines.append(' '.join(current_line))

        return lines

    def generate_text_image(self):
        try:
            # 获取输入参数
            width = int(self.m_TextImageWidth.GetValue())  # 图片高
            height = int(self.m_TextImageHeight.GetValue())
            font_size = int(self.m_textFontSize.GetValue())
            text = self.m_textSingleTextContent.GetValue().strip()

            if not text:
                wx.MessageBox("请输入文字内容", "错误", wx.OK | wx.ICON_ERROR)
                return

            # 创建图片
            image = Image.new('RGB', (width, height), color=(255, 255, 255))
            draw = ImageDraw.Draw(image)

            # 尝试使用系统字体
            try:
                font = ImageFont.truetype("simsun.ttf", font_size)
            except:
                try:
                    font = ImageFont.truetype("simsun", font_size)
                except:
                    font = ImageFont.load_default()

            # 计算文字位置和自动换行
            lines = self.wrap_text(text, font, width - 40)  # 留出边距

            # 计算总文本高度
            total_height = 0
            line_heights = []
            for line in lines:
                bbox = draw.textbbox((0, 0), line, font=font)
                line_height = bbox[3] - bbox[1]
                line_heights.append(line_height)
                total_height += line_height + 5  # 5像素的行间距

            # 垂直居中
            y = (height - total_height) // 2

            # 绘制每一行文字
            for i, line in enumerate(lines):
                bbox = draw.textbbox((0, 0), line, font=font)
                line_width = bbox[2] - bbox[0]
                x = (width - line_width) // 2
                draw.text((x, y), line, font=font, fill=(0, 0, 0))  # self.font_color)
                y += line_heights[i] + 5  # 行间距

            self.current_image = image

            # 显示预览
            # image.show()

        except ValueError:
            wx.MessageBox("请输入有效的数字", "错误", wx.OK | wx.ICON_ERROR)
        except Exception as e:
            wx.MessageBox(f"生成图片时出错: {str(e)}", "错误", wx.OK | wx.ICON_ERROR)

    def on_save_text_image(self):
        if self.current_image:
            with wx.FileDialog(self, "保存图片", wildcard="PNG files (*.png)|*.png|JPEG files (*.jpg)|*.jpg",
                               style=wx.FD_SAVE | wx.FD_OVERWRITE_PROMPT) as file_dialog:

                if file_dialog.ShowModal() == wx.ID_CANCEL:
                    return

                file_path = file_dialog.GetPath()
                try:
                    # 根据文件扩展名确定格式
                    if file_path.lower().endswith('.jpg') or file_path.lower().endswith('.jpeg'):
                        format = 'JPEG'
                    else:
                        format = 'PNG'
                        if not file_path.lower().endswith('.png'):
                            file_path += '.png'

                    self.current_image.save(file_path, format=format)
                    wx.MessageBox(f"图片已保存到: {file_path}", "成功", wx.OK | wx.ICON_INFORMATION)
                except Exception as e:
                    wx.MessageBox(f"保存图片时出错: {str(e)}", "错误", wx.OK | wx.ICON_ERROR)
        else:
            wx.MessageBox("请先生成图片", "警告", wx.OK | wx.ICON_WARNING)

    def GetViewAndGridImageFilePath(self):
        return self.m_filePickerLoadImageForViewAndGrid.GetPath()

    def GetSplitCellWidth(self):
        return int(self.m_textCtrlSplitCellWidth.GetValue())

    def GetSplitCellHeight(self):
        return int(self.m_textCtrlSplitCellHeight.GetValue())

    # 拿到切割图的单图片名字
    def GetSplitCellName(self):
        # 后面再做异常处理了
        return self.m_textCtrlSplitCellName.GetValue()

    # 拿到切割图的存放目录
    def GetSplitCellImageOutputPath(self):
        # 和面再做异常处理
        return self.m_dirPickerSplitImagePath.GetPath()

    def GetScaleValue(self):
        try:
            return float(self.m_textCtrlScale.GetValue())
        except Exception as e:
            print(f"转换失败，发生错误：{e},将会返回缩放值1")
            return 1

    # 生成新的图片
    def GenerateNewImage(self):
        self.m_listBoxOutputFiles.Clear()
        img_count = self.m_listBoxSrcImage.GetCount()
        for i in range(img_count):
            srcImagePath = self.m_listBoxSrcImage.GetString(i)
            print(f"第 {i} 项:", srcImagePath)
            transparent_color = GetColorTupleFromPicker(self.m_colourPickerTransparent)
            scale = self.GetScaleValue()
            file_name_base = ImageTools.get_filename_without_extension(srcImagePath)

            # 在这里 self.m_checkBoxUseTransparentColor
            result_img = None

            if self.m_checkBoxUseTransparentColor.IsChecked():
                result_img = ImageTools.convert_to_rgba_with_transparency(srcImagePath, transparent_color, scale)
            else:
                result_img = ImageTools.resize_image(srcImagePath, scale)

            output_dir = self.m_dirPickerOutputDir.GetPath()
            output_file_path = os.path.join(output_dir, file_name_base + self.m_comboBoxSuffix.GetValue())
            self.m_listBoxOutputFiles.Append(output_file_path)
            result_img.save(output_file_path, format="png")
